export const PRODUCT_ID = "PRODUCT_ID";
export const PRODUCT_QUANTITY = "PRODUCT_QUANTITY";
export const PRODUCT_NAME = "PRODUCT_NAME";
export const PRODUCT_DESCRIPTION = "PRODUCT_DESCRIPTION";
export const PRODUCT_TOTALPRICE = "PRODUCT_TOTALPRICE";
export const RESET_PRODUCT = "RESET_PRODUCT";
export const ORDER_STATE = "ORDER_STATE";